/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Incredible Crisis)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x8015F91Cu
#define func_8015F91C BootEntry  /* alias */
